spring:
  application:
    name: ums
  profiles:
    active: dev      
  datasource:
    url: jdbc:oracle:thin:@10.12.4.203:1522/RIFAH
    username: UMSDM
    password: UMSDM
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 60000       # in milliseconds
      connection-timeout: 30000 # in milliseconds    
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
      
  jpa:
    hibernate:
      ddl-auto: none     # change to 'update' only for dev; 'none' is safer for production
    properties:
      jakarta.persistence.schema-generation.database.action: none
      hibernate.default_schema: UMSDM
    show-sql: true
    #database-platform: org.hibernate.dialect.OracleDialect
  security:
    user:
      name: admin
      password: "{noop}admin"
jwt:
  secret: U1BSSU5HU0VDUklUX1NFTkNfMzI1Nl9CSVNfQ0hBTExFTkdF
